// 상품 데이터
export const products = [
  { id: 1,
    name: '코난 그레이 내한공연',
    //description: 'Description for product 1',
    interpark: "https://tickets.interpark.com/goods/24006288",
    yes24: "",
    image: "https://ticketimage.interpark.com/Play/image/large/24/24006288_p.gif",
    tags: "#서울 #내한 #콘서트 #팝 "},
    
  { id: 2,
    name: '<미스트롯3> 전국투어 콘서트 - 광주',
    //description: 'Description for product 2',
    interpark: "https://tickets.interpark.com/goods/24003268",
    yes24: "",
    image: "https://ticketimage.interpark.com/Play/image/large/24/24003268_p.gif",
    tags: "#광주 #콘서트 #트로트 "},

  { id: 3,
    name: '2024 서울파크뮤직페스티벌',
    //description: 'Description for product 3',
    interpark: "https://tickets.interpark.com/goods/24001672",
    yes24: "",
    image: "https://ticketimage.interpark.com/Play/image/large/24/24001672_p.gif",
    tags: "#서울 #페스티벌 #밴드 #락 "},

  { id: 4,
    name: '2024 인천 펜타포트 락 페스티벌',
    //description: 'Description for product 4',
    interpark: "https://tickets.interpark.com/goods/24005722",
    yes24: "http://ticket.yes24.com/Perf/49633",
    image: "https://ticketimage.interpark.com/Play/image/large/24/24005722_p.gif",
    tags: "#인천 #페스티벌 #밴드 #락 "},

  { id: 5,
    name: '옥탑 재즈 III',
    //description: 'Description for product 5',
    interpark: "https://tickets.interpark.com/goods/24003645",
    yes24: "",
    image: "https://ticketimage.interpark.com/Play/image/large/24/24003645_p.gif",
    tags: "#인천 #콘서트 #재즈 "},

  { id: 6,
    name: '먼데이프로젝트 시즌7 ［윤딴딴 부산 단독 콘서트 ‘순간의 노래’］ - 부산',
    //description: 'Description for product 6',
    interpark: "https://tickets.interpark.com/goods/24006666",
    yes24: "",
    image: "https://ticketimage.interpark.com/Play/image/large/24/24006666_p.gif",
    tags: "#부산 #콘서트 #발라드 "},

  { id: 7,
    name: 'World DJ Festival 2024',
    //description: 'Description for product 7',
    interpark: "https://tickets.interpark.com/goods/23017356",
    yes24: "",
    image: "https://ticketimage.interpark.com/Play/image/large/23/23017356_p.gif",
    tags: "#서울 #페스티벌 #락 #EDM "},

  { id: 8,
    name: '올리비아 로드리고 첫 내한공연',
    //description: 'Description for product 8',
    interpark: "https://tickets.interpark.com/goods/24006714",
    yes24: "",
    image: "https://ticketimage.interpark.com/Play/image/large/24/24006714_p.gif",
    tags: "#서울 #내한 #콘서트 #팝 "},

  { id: 9,
    name: '2024 박정현 소극장 콘서트 [이음]',
    //description: 'Description for product 8',
    interpark: "https://tickets.interpark.com/goods/24006782",
    yes24: "",
    image: "https://ticketimage.interpark.com/Play/image/large/24/24006782_p.gif",
    tags: "#서울 #콘서트 #발라드 "},

  { id: 10,
    name: '2024 월간뮤지크 <소란>',
    //description: 'Description for product 8',
    interpark: "https://tickets.interpark.com/goods/24007135",
    yes24: "",
    image: "https://ticketimage.interpark.com/TicketImage/main/common/mobile/noimage_vtc.jpg",
    tags: "#서울 #콘서트 #밴드 "},
];


